apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-tenant-operator
  namespace: default
  labels:
    app: mongodb-tenant-operator
spec:
  selector:
    matchLabels:
      app: mongodb-tenant-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-tenant-operator
    spec:
      containers:
      - name:  mongodb-tenant-operator
        image: ghcr.io/paulrostorp/k8s-mongodb-tenant-operator:latest
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 150Mi
        env:
        - name: MONGO_CLUSTER_ADMIN_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-admin-credentials
              key: MONGO_DB_HOST
      restartPolicy: Always