apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-tenant-operator-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: mongodb-tenant-operator-cluster-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "delete", "create"]
  - apiGroups: ["mongotenantoperator.com"] # "" indicates the core API group
    resources:
      ["mongodbusers", "mongodbusers/status", "mongodbusers/finalizers"]
    verbs: ["get", "watch", "update", "patch", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: mongodb-tenant-operator-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: mongodb-tenant-operator-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: mongodb-tenant-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
